name: Nightly CNN-LSTM Train

on:
  schedule:
    - cron: "30 2 * * *"   # 02:30 UTC daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # TensorFlow 2.15 works well on 3.10

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account JSON (temp)
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          set -euxo pipefail
          echo "$GOOGLE_SHEETS_JSON" > "$RUNNER_TEMP/sa.json"
          python - <<'PY'
          import json, os
          p = os.path.join(os.environ["RUNNER_TEMP"], "sa.json")
          json.load(open(p))
          print("Service account JSON OK:", p)
          PY

      - name: Put service account at gspread default path
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          set -euxo pipefail
          mkdir -p "$HOME/.config/gspread"
          echo "$GOOGLE_SHEETS_JSON" > "$HOME/.config/gspread/service_account.json"
          ls -al "$HOME/.config/gspread"
          python - <<'PY'
          import json, os
          p = os.path.expanduser("~/.config/gspread/service_account.json")
          json.load(open(p))
          print("Service account JSON OK at:", p)
          PY

      - name: Sanity write to Google Sheet (CI Health tab)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa.json
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python - <<'PY'
          import os, gspread
          tab = "CI Health"
          gc = gspread.service_account(filename=os.environ["GOOGLE_APPLICATION_CREDENTIALS"])
          sh = gc.open_by_key(os.environ["SHEET_ID"])
          try:
              ws = sh.worksheet(tab)
          except Exception:
              ws = sh.add_worksheet(title=tab, rows=1000, cols=26)
          ws.append_row(["CI smoke test (CNN-LSTM)", "ok"])
          print(f"Wrote a row to '{tab}'")
          PY

      - name: Prepare daily cache key
        run: echo "CACHE_DATE=$(date -u +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Cache price data
        uses: actions/cache@v4
        with:
          path: data_cache
          key: stooq-yf-${{ env.CACHE_DATE }}
          restore-keys: |
            stooq-yf-

      - name: Show train.py help (to confirm flags)
        run: |
          python train.py --help || true

      - name: Train CNN-LSTM and write to its own tab
        id: train
        continue-on-error: true
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/sa.json
          SHEET_ID: ${{ secrets.SHEET_ID }}
          WORKSHEET_NAME: watchlist_cnnlstm
        run: |
          set -euxo pipefail
          LOG="$GITHUB_WORKSPACE/train_cnn_lstm.log"
          python train.py \
            --model cnn-lstm \
            --sheet-id "$SHEET_ID" \
            --worksheet "$WORKSHEET_NAME" \
            --symbol-column "Ticker" \
            --period 1y \
            --interval 1d \
            2>&1 | tee "$LOG"

      - name: Upload training log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: train-cnnlstm-log
          path: ${{ github.workspace }}/train_cnn_lstm.log

      - name: Commit model artifacts (optional)
        if: steps.train.outcome == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/cnn_lstm_ALL.keras models/scaler_ALL.pkl || true
          git commit -m "Update CNN-LSTM weights ($(date -u +%F))" || echo "No changes"
          git push
