name: Retrain Linear (daily)

on:
  workflow_dispatch: {}
  schedule:
    # Run weekdays ~ 1:15 PM PT (DST-safe because script gates by PT time)
    - cron: "15 21 * * 1-5"  # 21:15 UTC ≈ 13:15 PT (PDT/PST varies; script double-checks)

permissions:
  contents: write  # allow commit of model file

concurrency:
  group: retrain-linear
  cancel-in-progress: true

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 pandas==2.2.2 scikit-learn==1.4.2 joblib==1.4.2 yfinance==0.2.44 requests==2.32.3

      - name: Retrain linear model (after-close gate inside)
        run: |
          python scripts/retrain_linear.py --days ${DAYS:-365} --out models/linear_model.pkl

      - name: Commit model if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/linear_model.pkl
          if ! git diff --cached --quiet; then
            git commit -m "ci: update linear_model.pkl [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
