name: Retrain Linear

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy yfinance scikit-learn joblib gspread oauth2client -r requirements.txt

      - name: Train
        run: python train_linear.py

      - name: Commit model artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/linear_ALL.pkl models/scaler_ALL.pkl
          git commit -m "Update Linear model artifacts" || echo "No changes to commit"
          git push
