name: Nightly CNN-LSTM Train (BACKUP)
on:
  schedule:
    - cron: "30 2 * * *"   # 02:30 UTC daily (10:30 AM Manila, UTC+8)
  workflow_dispatch: {}     # lets you run it manually from the UI

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-cpu==2.15.* pandas numpy yfinance scikit-learn joblib

      - name: Train
        run: python train.py

      - name: Commit model artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/cnn_lstm_ALL.keras models/scaler_ALL.pkl
          git commit -m "Update CNN-LSTM weights ($(date -u +%Y-%m-%d))" || echo "No changes"
          git push
